supervalu:
  opt_1:
    name: SuperValu Fresh Irish Beef Round Steak Mince
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-fresh-irish-beef-round-steak-mince-454-g-id-1390464002
    price: €3.00 was €4.99
    price_per_unit: €6.61/kg
    quantity: 454 g
