supervalu:
  opt_1:
    name: Fitzgeralds Wholemeal Wraps 6 Pack
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/fitzgeralds-wholemeal-wraps-6-pack-370-g-id-1174452001
    price: €2.45
    price_per_unit: €6.62/kg
    quantity: 370 g
