supervalu:
  opt_2:
    name: SuperValu Mild Onions
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-mild-onions-3-piece-id-1068150000
    price: €1.49
    price_per_unit: €0.50 each
    quantity: 3 Piece
  opt_3:
    name: Supervalu Onions Net
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-onions-net-750-g-id-1258724000
    price: €0.99
    price_per_unit: €1.32/kg
    quantity: 750 g
  opt_1:
    name: SuperValu Red Onion
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-red-onion-1-kg-id-1036692000
    price: €2.19/kg
    price_per_unit: €2.19/kg
    quantity: 1 kg
