supervalu:
  opt_2:
    name: SuperValu Red Onions
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-red-onions-750-g-id-1258724002
    price: €1.05
    price_per_unit: €1.40/kg
    quantity: 750 g
  opt_3:
    name: Loose Brown Onion
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/loose-brown-onion-1-kg-id-1036706000
    price: €2.89/kg
    price_per_unit: €2.89/kg
    quantity: 1 kg
  opt_1:
    name: SuperValu Brown Onions
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-brown-onions-750-g-id-1017016001
    price: €1.05
    price_per_unit: €1.40/kg
    quantity: 750 g
