supervalu:
  opt_2:
    name: SuperValu Red Onion
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-red-onion-1-kg-id-1036692000
    price: €2.19/kg
    price_per_unit: €2.19/kg
    quantity: 1 kg
  opt_1:
    name: SuperValu Red Onions
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-red-onions-750-g-id-1258724002
    price: €1.05
    price_per_unit: €1.40/kg
    quantity: 750 g
  opt_3:
    name: SuperValu Organic Red Onions
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-organic-red-onions-500-g-id-1443406001
    price: €1.89
    price_per_unit: €3.78/kg
    quantity: 500 g
