supervalu:
  opt_1:
    name: SuperValu Signature Tastes Superfood Salad
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-signature-tastes-superfood-salad-150-g-id-1663027000
    price: €2.09
    price_per_unit: €13.93/kg
    quantity: 150 g
