supervalu:
  opt_1:
    name: SuperValu Growing Coriander (1 Piece)
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-growing-coriander-1-piece-id-1027601000
    price: €1.69
    price_per_unit: €1.69
