supervalu:
  opt_1:
    name: SuperValu Fresh Basil
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-fresh-basil-20-g-id-1592795002
    price: €1.19
    price_per_unit: €59.50/kg
    quantity: 20 g
  opt_2:
    name: SuperValu Growing Basil
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-growing-basil-1-piece-id-1027577000
    price: €1.69
    price_per_unit: €1.69
    quantity: 1 Piece
  opt_3:
    name: Rummo Basil Pesto
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/rummo-basil-pesto-190-g-id-1776117000
    price: €5.09
    price_per_unit: €26.79/kg
    quantity: 190 g
