supervalu:
  opt_1:
    name: SuperValu Large Fresh Irish Eggs 12 Pack (12 Piece)
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-large-fresh-irish-eggs-12-pack-12-piece-id-1024956000
    price: €2.99
    price_per_unit: €0.25 each
    quantity: 12 Piece

