supervalu:
  opt_1:
    name: Melitta Coffee Filters 40 Pack
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/melitta-coffee-filters-40-pack-40-piece-id-1020136000
    price: €2.30
    price_per_unit: €0.06 each
    quantity: 40 Piece
