supervalu:
  opt_1:
    name: SuperValu Strawberry Kefir
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/biotiful-gut-health-original-kefir-drink-1-l-id-1952840000
    price: €2.00
    price_per_unit: €4.00/l
    quantity: 500 ml
