supervalu:
  opt_1:
    name: SuperValu Coconut Milk
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-coconut-milk-400-ml-id-1729176000
    price: €0.95
    price_per_unit: €2.38/l
    quantity: 400 ml
