supervalu:
  opt_1:
    name: Schwartz Spices Garam Masala
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/schwartz-spices-garam-masala-30-g-id-1024796000
    price: €3.05
    price_per_unit: €101.67/kg
    quantity: 30 g
