supervalu:
  opt_2:
    name: SuperValu Signature Tastes Buffalo Mozzarella Cheese
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-signature-tastes-buffalo-mozzarella-cheese-125-g-id-1209960000
    price: €2.89
    price_per_unit: €23.12/kg
    quantity: 125 g
  opt_1:
    name: Macroom Buffalo Irish Mozzarella
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/macroom-buffalo-irish-mozzarella-125-g-id-1448230000
    price: €3.39
    price_per_unit: €27.12/kg
    quantity: 125 g
