supervalu:
  opt_1:
    name: SuperValu Beef Tomatoes
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-beef-tomatoes-2-piece-id-1600884000
    price: €2.35
    price_per_unit: €1.18 each
    quantity: 2 Piece
  opt_3:
    name: SuperValu Cherry Tomatoes
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-cherry-tomatoes-250-g-id-1010962000
    price: €1.09
    price_per_unit: €4.36/kg
    quantity: 250 g
  opt_2:
    name: SuperValu Tomatoes
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-tomatoes-6-piece-id-1016514000
    price: €1.29
    price_per_unit: €0.22 each
    quantity: 6 Piece
