supervalu:
  opt_1:
    name: SuperValu Easy Cook Long Grain Rice
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-easy-cook-long-grain-rice-1-kg-id-1009603000
    price: €1.65
    price_per_unit: €1.65/kg
    quantity: 1 kg
