supervalu:
  opt_1:
    name: Schwartz Bay Leaves
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/schwartz-bay-leaves-3-g-id-1723634000
    price: €2.50
    price_per_unit: €833.33/kg
    quantity: 3 g
