supervalu:
  opt_1:
    name: Avonmore Lactose Free Milk
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/avonmore-lactose-free-milk-1-l-id-1048842000
    price: €2.19
    price_per_unit: €2.19/l
    quantity: 1 L
