supervalu:
  opt_1:
    name: SuperValu Raisins
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-raisins-375-g-id-1007995000
    price: €1.89
    price_per_unit: €5.04/kg
    quantity: 375 g
  opt_2:
    name: Daily Basics Raisins
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/daily-basics-raisins-375-g-id-1347405000
    price: €1.05
    price_per_unit: €2.80/kg
    quantity: 375 g
  opt_3:
    name: Nestle Yorkie Raisin & Biscuit
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/nestle-yorkie-raisin-&-biscuit-44-g-id-1027343002
    price: €2.20
    price_per_unit: €50.00/kg
    quantity: 44 g
