supervalu:
  opt_1:
    name: Oral-B Pro-Expert Healthy Whitening Toothpaste (75 ml)
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/oralb-proexpert-healthy-whitening-toothpaste-75-ml-id-1209695001
    price: €3.50
    price_per_unit: €46.67/l
    quantity: 75 ml
