supervalu:
  opt_1:
    name: Lakeshore Groundnut Peanut Oil
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/lakeshore-groundnut-peanut-oil-500-ml-id-1061832000
    price: €5.99
    price_per_unit: €11.98/l
    quantity: 500 ml
