supervalu:
  opt_1:
    name: Loose Hake Fillets
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/loose-hake-fillets-1-kg-id-1028898000
    price: €25.99/kg
    price_per_unit: €25.99/kg
    quantity: 1 kg
