supervalu:
  opt_1:
    name: Butternut Squash Loose
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/butternut-squash-loose-1-piece-id-1027497000
    price: €1.19
    price_per_unit: €1.19
    quantity: 1 Piece
