supervalu:
  opt_1:
    name: SuperValu Fresh Irish Pork Mince
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-fresh-irish-pork-mince-400-g-id-1350028000
    price: €3.00
    price_per_unit: €7.50/kg
    quantity: 400 g
