supervalu:
  opt_1:
    name: SuperValu Light Red Grated Cheddar Cheese (200 g)
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-light-red-grated-cheddar-cheese-200-g-id-1033911000
    price: €2.05
    price_per_unit: €10.25/kg
    quantity: 200 g
