supervalu:
  opt_3:
    name: Schwartz Black Pepper Coarse Ground Jar
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/schwartz-black-pepper-coarse-ground-jar-33-g-id-1004861000
    price: €3.20
    price_per_unit: €96.97/kg
    quantity: 33 g
  opt_1:
    name: Saxa Pepper Black Ground
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/saxa-pepper-black-ground-25-g-id-1015269000
    price: €1.40
    price_per_unit: €56.00/kg
    quantity: 25 g
  opt_2:
    name: Schwartz Black Pepper Ground Jar
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/schwartz-black-pepper-ground-jar-33-g-id-1004862000
    price: €3.20
    price_per_unit: €96.97/kg
    quantity: 33 g
