supervalu:
  opt_1:
    name: SuperValu Signature Tastes Prosciutto Di Parma Ham
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-signature-tastes-prosciutto-di-parma-ham-100-g-id-1342493000
    price: €3.10
    price_per_unit: €31.00/kg
    quantity: 100 g
