supervalu:
  opt_1:
    name: SuperValu Signature Tastes Gold Kiwis
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-signature-tastes-gold-kiwis-4-piece-id-1008873000
    price: €3.50
    price_per_unit: €0.88 each
    quantity: 4 Piece
