supervalu:
  opt_1:
    name: SuperValu Loose Limes
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-loose-limes-1-piece-id-1015786000
    price: €0.49
    price_per_unit: €0.49
    quantity: 1 Piece
