supervalu:
  opt_1:
    name: Keogh's Fresh Potatoes
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/keoghs-fresh-potatoes-2-kg-id-1389480000
    price: €3.49
    price_per_unit: €1.75/kg
    quantity: 2 kg
