supervalu:
  opt_2:
    name: Heinz Tomato Bolognese Pasta Sauce
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/heinz-tomato-bolognese-pasta-sauce-490-g-id-1882775000
    price: €3.79
    price_per_unit: €7.73/kg
    quantity: 490 g
  opt_1:
    name: SuperValu Signature Tastes Traditional Bolognese Pasta Sauce
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-signature-tastes-traditional-bolognese-pasta-sauce-350-g-id-1350410000
    price: €2.50
    price_per_unit: €7.14/kg
    quantity: 350 g
  opt_3:
    name: Heinz Tomato Bolognese Pasta Sauce
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/heinz-tomato-bolognese-pasta-sauce-350-g-id-1882122004
    price: €2.50
    price_per_unit: €7.14/kg
    quantity: 350 g
