supervalu:
  opt_1:
    name: Roma Tomato Puree Tubes
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/roma-tomato-puree-tubes-140-g-id-1007760000
    price: €1.50
    price_per_unit: €10.71/kg
    quantity: 140 g
