supervalu:
  opt_1:
    name: Biona Organic Whole Plum Peeled Tomatoes
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/biona-organic-whole-plum-peeled-tomatoes-400-g-id-1057423000
    price: €1.99
    price_per_unit: €4.98/kg
    quantity: 400 g
