supervalu:
  opt_1:
    name: SuperValu Sweet Bell Peppers
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-sweet-bell-peppers-500-g-id-1622607000
    price: €2.39
    price_per_unit: €4.78/kg
    quantity: 500 g
