supervalu:
  opt_2:
    name: Irish Pride Sandwich White Half Pan
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/irish-pride-sandwich-white-half-pan-400-g-id-1017202000
    price: €1.79
    price_per_unit: €4.48/kg
    quantity: 400 g
  opt_1:
    name: Irish Pride Sandwich White Sliced Pan
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/irish-pride-sandwich-white-sliced-pan-800-g-id-1016048000
    price: €1.99
    price_per_unit: €2.49/kg
    quantity: 800 g
