supervalu:
  opt_1:
    name: SuperValu Radish
    url: https://shop.supervalu.ie/sm/delivery/rsid/404/product/supervalu-radish-200-g-id-1084671000
    price: €0.89
    price_per_unit: €4.45/kg
    quantity: 200 g
